# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 1

rate: 50
sensorstate_rate: 10

use_base_controller: true
base_controller_rate: 10

pid_rate: 20

# For a robot that uses base_footprint, change base_frame to base_footprint (default base_frame: base_link)
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.065
wheel_track: 0.174
encoder_resolution: 20 # ticks per revolution 
gear_reduction: 1.0
#motors_reversed: True

# === PID parameters (100, 90, 3, 30)
Kp: 0.07
Kd: 0.01
Ki: 0.02
# Ko not used
Ko: 20
accel_limit: 0.1

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  #arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
